version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Instalando jq..."
      - apt-get update && apt-get install -y jq
  build:
    commands:
      - echo "Construyendo la imagen Docker..."
      - docker build -t $ECR_REPO:latest .
      - docker tag $ECR_REPO:latest $ECR_REPO:latest
  post_build:
    commands:
      - echo "Empujando la imagen a Amazon ECR..."
      - docker push $ECR_REPO:latest
      - echo "Generando imagedefinitions.json..."
      - ImageURI=$(jq -r '.ImageURI' imageDetail.json)
      - printf '[{"name":"mi-contenedor","imageUri":"%s"}]' "$ImageURI" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
